config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'welcome/index'
  root 'welcome#index'
  resources :terms
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/term.rb
class Term < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :subject)
    end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  before_action :set_term, only: [:show, :edit, :update, :destroy]

  # GET /terms
  # GET /terms.json
  def index
    @terms = Term.all
  end

  # GET /terms/1
  # GET /terms/1.json
  def show
  end

  # GET /terms/new
  def new
    @term = Term.new
  end

  # GET /terms/1/edit
  def edit
  end

  # POST /terms
  # POST /terms.json
  def create
    @term = Term.new(term_params)

    respond_to do |format|
      if @term.save
        format.html { redirect_to @term, notice: 'Term was successfully created.' }
        format.json { render :show, status: :created, location: @term }
      else
        format.html { render :new }
        format.json { render json: @term.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /terms/1
  # PATCH/PUT /terms/1.json
  def update
    respond_to do |format|
      if @term.update(term_params)
        format.html { redirect_to @term, notice: 'Term was successfully updated.' }
        format.json { render :show, status: :ok, location: @term }
      else
        format.html { render :edit }
        format.json { render json: @term.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /terms/1
  # DELETE /terms/1.json
  def destroy
    @term.destroy
    respond_to do |format|
      format.html { redirect_to terms_url, notice: 'Term was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_term
      @term = Term.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def term_params
      params.require(:term).permit(:name, :definition, :author, :resource)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @terms = Term.all.order(created_at: :desc).take(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :subject %>
    <%= f.text_field :subject %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Subject</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.subject %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @category.subject %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TYGlossary</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
    <h1>Our &spades;Awesome&spades; Glossary</h1>
    <div class="right_nav">
      <button>
        <a href="/terms">
          <%= image_tag "t.png" %>
          <%= image_tag "e.png" %>
          <%= image_tag "r.png" %>
          <%= image_tag "m.png" %>
          <%= image_tag "s.png" %>
        </a>
      </button>

      <button>
        <a href="/categories">
          <%= image_tag "c.png" %>
          <%= image_tag "a.png" %>
          <%= image_tag "t.png" %>
          <%= image_tag "e.png" %>
          <%= image_tag "g.png" %>
          <%= image_tag "o.png" %>
          <%= image_tag "r.png" %>
          <%= image_tag "i.png" %>
          <%= image_tag "e.png" %>
          <%= image_tag "s.png" %>
        </a>
      </button>

      <!-- <button>
        <form action="/terms/search" method="post">
          <input type="text" name="name" placeholder="Search...">
          <input type="image" src="search.png" />
        </form>
      </button> -->
    </div>
  </header>
  <body>
    <%= yield %>
  </body>
</html>

app/views/terms/_form.html.erb
<%= form_for(term) do |f| %>
  <% if term.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(term.errors.count, "error") %> prohibited this term from being saved:</h2>

      <ul>
      <% term.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :definition %>
    <%= f.text_field :definition %>
  </div>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>

  <div class="field">
    <%= f.label :resource %>
    <%= f.text_field :resource %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/terms/edit.html.erb
<h1>Editing Term</h1>

<%= render 'form', term: @term %>

<%= link_to 'Show', @term %> |
<%= link_to 'Back', terms_path %>

app/views/terms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Terms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Definition</th>
      <th>Author</th>
      <th>Resource</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @terms.each do |term| %>
      <tr>
        <td><%= term.name %></td>
        <td><%= term.definition %></td>
        <td><%= term.author %></td>
        <td><%= term.resource %></td>
        <td><%= link_to 'Show', term %></td>
        <td><%= link_to 'Edit', edit_term_path(term) %></td>
        <td><%= link_to 'Destroy', term, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Term', new_term_path %>

app/views/terms/new.html.erb
<h1>New Term</h1>

<%= render 'form', term: @term %>

<%= link_to 'Back', terms_path %>

app/views/terms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @term.name %>
</p>

<p>
  <strong>Definition:</strong>
  <%= @term.definition %>
</p>

<p>
  <strong>Author:</strong>
  <%= @term.author %>
</p>

<p>
  <strong>Resource:</strong>
  <%= @term.resource %>
</p>

<%= link_to 'Edit', edit_term_path(@term) %> |
<%= link_to 'Back', terms_path %>

app/views/welcome/index.html.erb
<h1>5 Most Recent Terms</h1>
<div class="most_recent">
  <% @terms.each do |term| %>
    <a href="/terms/<%= term.id %>"><%= term.name %></a>
    <br>
  <% end %>
</div>